### ISSUE TITLE
Personel oluşturma

### ISSUE THREAD

**Issue by fatihGunalp** [gulsenruya/NTierProjects#1]
Form1.cs içerisinde personel oluşturma işlemleri tamamlanacak. Personel oluşturulduktan sonra DesignPattern olarak CreationalFactory kullanarak Departman'a göre yetkilendirme işlemi gerçekleştirilecek. Örn;

Personellerden Muhasebe personeli ekleme esnasında daha önce işlenen MobilPlatform uygulamasında olduğu gibi Yetki ve yetki oluşturma nesneneleri tanımlanacak. Böylece Muhasebe departmanın yetkisini uygulama içerisinden verilecek.

**Comment by gulsenruya** [comment]
Tamamlandı 
(https://github.com/gulsenruya/NTierProjects/tree/master/NTierPersonelEkleme)
